### ISSUE TITLE
 💖 looking for goss maintainers

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-goss#6]
I am unable to maintain this driver as I am not using it, so I am looking for maintainers.

I can keep providing support for integration with molecule itself but not around vagrant bits.

I would work noting that the top priority would be to setup CI jobs.

**Comment by belfast77** [comment]
very happy to help if I can with my skill set.

I can get a gitlab-ci going and document it.

**Comment by ssbarnea** [comment]
@belfast77 I invited you, from now one future of molecule-goss is in you hands.

PS. The invitation is still open.

**Comment by belfast77** [comment]
Thanks very much @zbr, accepted but shall we leave this open in case we get an offer of help from others with more relevant skill set ?

**Comment by filicivi** [comment]
Maybe I'm wrong but.. is this driver really helpful?
I mean, you can use verify.yml to template gossfiles using ansible vars and run goss in the remote machine.

**Comment by ssbarnea** [comment]
Theoretically you could use only ansible to test ansible and avoid molecule. Still, how easy is to do it and how much boilerpate code you have to write is s another question.

**Comment by abtreece** [comment]
Hey @ssbarnea since the Goss implementation is so similar to Inspec I should be able to help shepherd this plugin along as well.

**Comment by ssbarnea** [comment]
@abtreece Welcome aboard! I will keep this open until we gave at least two maintainers. I would not count myself as one.

**Comment by ssbarnea** [comment]
Archiving project due to lack of maintainers
